packages:
  # - apps/*
  - packages/*
  - '!packages/gc-validators'
  - gcemail/
allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@swc/core': set this to true or false
  better-sqlite3: set this to true or false
  core-js-pure: set this to true or false
  esbuild: true
  sharp: set this to true or false
  sqlite3: set this to true or false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@getcommunity/config-prettier@0.1.6'
  - '@getcommunity/config-typescript@0.0.25'
